export default {
    spacer:{
        width:'100%',
        height:'30px'
    },
    spacerHalf:{
        width:'100%',
        height:'15px'
    },
    absCenter:{
        position:'absolute',
        top:'25%',
        left:'50%',
        transform:'translate(-50%, -50%)',
        textAlign:'center'
    },
    noMargin:{
        margin:'0'
    },
    noPadding:{
        padding:'0'
    },
    background:{
        margin:'0',
        padding:'10px',
        borderRadius:'0',
        boxShadow:'0 1px 2px rgba(0,0,0,.3)'
    },
    body:{
        backgroundColor:'#f1f1f1',
        minHeight:'100vh'
    },
    headerFont:{
        color:'#fff',
        fontWeight:'300'
    },
    header:{
        padding:'0',
        margin:'0',
    },
    backgroundColorOne:{
        backgroundColor:'#5a7185',
    },
    backgroundColorTwo:{
        backgroundColor:'#fff',
    },
    backgroundColorThree:{
        backgroundColor:'#fff',
    },
    backgroundColorFour:{
        backgroundColor:'#fff',
        margin:'0',
        padding:'10px',
        borderRadius:'0',
        boxShadow:'0 1px 2px rgba(0,0,0,.3)'
    },
    backgroundColorFive:{
        backgroundColor:'#fff',
    },
    backgroundColorSix:{
        backgroundColor:'#fff',
    },
    backgroundColorSeven:{
        backgroundColor:'#fff',
    },
    backgroundColorEight:{
        backgroundColor:'#fff',
    },
    backgroundColorNine:{
        backgroundColor:'#fff',
    },
    html:{
        padding:'25px'
    },
    noPaddingLeft:{
        paddingLeft:'0',
    },
    noPaddingRight:{
        paddingRight:'0',
    },
    submitBtn:{
        width:'100%',
        backgroundColor:'#5a7185',
        borderColor:'#5a7185',
    },
    commentContainer:{
        margin:'10px 0 0 0',
    },
    comment:{
        margin:'0 10px 10px',
    },
    commentHeader:{
    },
    commentBody:{
        color:'#a8a8a8'
    },
    fork:{
        position:'absolute',
        top:'0',
        right:'0',
        border:'0',
        zIndex:'99',
    },
    tweetContainer:{
    },
    tweet:{
    },
    container:{
    }
}